version: '3.4'

services:
  opencv_cam:
    image: opencv_cam
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./save:/save
    env_file:
      - ./var.env
    environment:
      - DISPLAY=unix:0
      - VIDEO=/dev/video0
